import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// when change top another page fade out then fade in
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-background mt-3 mr-32 ml-32`}>
        {children}
      </body>
    </html>
  );
}
